name: Deploy to IONOS Preprod
on:
  push:
    branches:
      - preprod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configuration de la clé SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.REPIT_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          ssh-keyscan -H access894124239.webspace-data.io >> ~/.ssh/known_hosts

      - name: Déploiement via SSH
        uses: appleboy/ssh-action@master
        with:
          host: access894124239.webspace-data.io
          username: u106767242
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /kunden/homepages/46/d894124239/htdocs/IllLovingDrivers
            git fetch origin preprod
            git reset --hard origin/preprod