name: Deploy to IONOS Preprod

on:
  push:
    branches:
      - preprod  # Déclenche le déploiement uniquement si un push est fait sur preprod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Configurer SSH
      run: |
        mkdir -p ~/.ssh
        echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H access894124239.webspace-data.io >> ~/.ssh/known_hosts
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa

    - name: Tester la connexion SSH
      run: |
        ssh -v u106767242@access894124239.webspace-data.io "echo 'Connexion réussie !'"

    
    - name: Déployer sur IONOS (Préprod)
      run: |
        ssh u106767242@access894124239.webspace-data.io << 'EOF'
          cd /kunden/homepages/46/d894124239/htdocs/IllLovingDrivers
          git pull origin preprod
        EOF

